dist: xenial
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - JEDI_TEST_ENVIRONMENT=27
  - JEDI_TEST_ENVIRONMENT=34
  - JEDI_TEST_ENVIRONMENT=35
  - JEDI_TEST_ENVIRONMENT=36

matrix:
  allow_failures:
    - python: pypy
    - env: TOXENV=sith
    - python: 3.7
  include:
    - python: 3.6
      env:
        - TOXENV=cov
        - JEDI_TEST_ENVIRONMENT=36
    - python: 3.6
      env: TOXENV=sith
    # For now ignore pypy, there are so many issues that we don't really need
    # to run it.
    #- python: pypy
install:
    - pip install --quiet tox-travis
script:
    - |
      set -x
      test_env_version=${JEDI_TEST_ENVIRONMENT:0:1}.${JEDI_TEST_ENVIRONMENT:1:1}
      if [ "$TRAVIS_PYTHON_VERSION" != "$test_env_version" ]; then
        python_bin=python$test_env_version
        if ! which $python_bin; then
          # Only required for JEDI_TEST_ENVIRONMENT=34.
          download_name=python-$test_env_version
          wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/$download_name.tar.bz2
          sudo tar xjf $download_name.tar.bz2 --directory / opt/python
          ln -s "/opt/python/${test_env_version}/bin/python" /home/travis/bin/$python_bin
        fi
        $python_bin --version
      fi
      set +x
    - tox
after_script:
    - |
      if [ $TOXENV == "cov" ]; then
        pip install --quiet codecov coveralls
        coverage xml
        coverage report -m
        coveralls
        bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X search -X fix -X xcode -f coverage.xml
      fi
