language: python
sudo: true
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - JEDI_TEST_ENVIRONMENT=27
  - JEDI_TEST_ENVIRONMENT=33
  - JEDI_TEST_ENVIRONMENT=34
  - JEDI_TEST_ENVIRONMENT=35
  - JEDI_TEST_ENVIRONMENT=36

matrix:
  allow_failures:
    - python: pypy
    - env: TOXENV=cov
    - env: TOXENV=sith
    - python: 3.7-dev
  include:
    - python: 3.5
      env: TOXENV=cov
    - python: 3.5
      env: TOXENV=sith
    - python: pypy
    - python: "3.7-dev"
install:
    - pip install --quiet tox-travis
script:
    - ./travis_install.sh
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet coveralls;
      coveralls;
      fi
