language: python
python:
    - 2.5
    - 2.6
    - 2.7
    - 3.2
install:
    # See: http://stackoverflow.com/questions/3241658/
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then
      sudo apt-get install libbluetooth-dev &&
      pip install --use-mirrors ssl;
      fi
    - pip install --use-mirrors tox
script:
    - export TOXENV=$(echo "$TRAVIS_PYTHON_VERSION" |
                      sed --regexp-extended 's/([0-9])\.([0-9])/py\1\2/g')
    - echo "TOXENV=$TOXENV"
    - tox
