language: python
python:
    - 2.5
    - 2.6
    - 2.7
    - 3.2
install:
    # Needed only for Python 2.5:
    - export PIP_INSECURE=t
    - pip install --use-mirrors tox
script:
    - export TOXENV=$(echo "$TRAVIS_PYTHON_VERSION" |
                      sed --regexp-extended 's/([0-9])\.([0-9])/py\1\2/g')
    - echo "TOXENV=$TOXENV"
    - tox
