language: python
env:
    - TOXENV=py25 PIP_INSECURE=t
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=cov
install:
    - pip install --quiet --use-mirrors tox coveralls
script:
    - tox
    - if [ $TOXENV == "cov" ]; then coveralls; fi
